### ISSUE TITLE
Allow TxRelay to send and receive ether

### ISSUE THREAD

**Issue by wjmelements** [uport-project/uport-identity#107]
I should be able to fund a TxRelay so it can issue transactions that require ether.

**Comment by oed** [comment]
Please have a look at the [contract documentation](https://github.com/uport-project/uport-identity#contract-documentation). The txRelay is only intended as a way to verify signatures. It is intended to be used in conjunction with the MetaIdentityManager and a Proxy contract. You can put ether in a proxy contract and send if from there. 
Hope that's helpful!
