### ISSUE TITLE
Usage in new libraries?

### ISSUE THREAD

**Issue by mesqueeb** [uport-project/uport-identity#110]
uport-identity was using an interesting implementation of Meta transactions in the TxRelay contract.
Is a similar approach also used in more up to date libraries of uPort?

**Comment by rmw2** [comment]
Hey @mesqueeb -- in updating our architecture to use the [ERC1056 specification](https://github.com/ethereum/EIPs/issues/1056), we no longer need to make a transaction to create an identity, and so the new identities (called `EthrDID`s, and conforming to the [w3c DID spec](https://w3c-ccg.github.io/did-spec/)) don't use meta transactions or the TxRelay Contract.
