### ISSUE TITLE
`MetaIdentityManager::addOwner()` can be called for existing owner

### ISSUE THREAD

**Issue by jessicagmarshall** [uport-project/uport-identity#64]
https://github.com/uport-project/uport-identity/blob/259435e45fc81167d137b33d40215a796b1cc091/contracts/MetaIdentityManager.sol#L127-L130

As either `addOwner()` function is written, a malicious olderOwner could call addOwner on an existing owner of `owner` or `olderOwner` status. This function call [overwrites](https://github.com/uport-project/uport-identity/blob/880f8b81b9355edfe62c35817562b24e90513d2a/contracts/IdentityManager.sol#L117) the time that existing owner became an owner in the `owners` mapping, and may be used as an attack to remove an older owner's admin privileges.

**Recommendation**

We recommend the addition of a `require` statement in both functions that ensures that `addOwner()` can only be called on an owner that is not a current owner.

**Comment by oed** [comment]
`require(!isOlderOwner(identity, newOwner))` should be sufficient right? This allows an older owner to "upgrade" a pending owner to owner status.

**Comment by jessicagmarshall** [comment]
It would still be possible for an olderOwner to downgrade an almost olderOwner to the beginning of owner status with that requirement, no? I see what you're saying - I think I that's a security/utility design trade off that should be deferred to you.

**Comment by oed** [comment]
Oh, I see. Yes you are correct, let's use `isOwner`!
