### ISSUE TITLE
documentation refers to nonexistent function

### ISSUE THREAD

**Issue by jessicagmarshall** [uport-project/uport-identity#65]
https://github.com/uport-project/uport-identity/blob/259435e45fc81167d137b33d40215a796b1cc091/docs/diagrams/send-tx.seq.puml#L9

* [Send a meta-tx](https://github.com/uport-project/uport-identity/blob/release/2.0.0/docs/diagrams/send-tx.seq.puml#L9)

A diagram that explains the control flow of a meta transaction refers to a `verifySignature()` function does not exist in the `TxRelay` contract. While its purpose may be inferred from the diagram, in the interest of exactness, verification of the meta transaction actually occurs as a require statement within the `relayMetaTx()` function in the `TxRelay` contract.

**Recommendation**

* update the documentation to reflect the `require()` statement

**Comment by oed** [comment]
I think when I wrote `verifySignature` I was not refering to a function but rather to behaviour. Since this functionallity doesn't take place in a function what should be written instead? Would `require(claimedSender == addressFromSig);` be sufficient?

**Comment by jessicagmarshall** [comment]
Yes, I think that would be sufficient.
